# Generated by Django 5.2.5 on 2025-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=30),
        ),
    ]
